# Generated by Django 5.0.6 on 2024-07-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfoliocategory_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Team/images')),
                ('description', models.TextField()),
                ('full_name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
    ]
